app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('__debug__/', include('debug_toolbar.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/images/urls.py
from django.urls import path
from .views import image_create, image_detail, image_like, image_list, image_ranking

app_name = 'images'

urlpatterns = [
    path('create/', image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', image_detail, name='detail'),
    path('like/', image_like, name='like'),
    path('', image_list, name='list'),
    path('ranking/', image_ranking, name='ranking')
]

app/images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            blank=True)
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    total_likes = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
            models.Index(fields=['-total_likes'])
        ]
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

    def save(self, *pargs, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*pargs, **kwargs)

app/images/forms.py
from django.core.files.base import ContentFile
from django.utils.text import slugify
from django import forms
from .models import Image
import requests


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'url', 'description']
        widgets = {
            'url': forms.HiddenInput
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()

        if extension not in valid_extensions:
            raise forms.ValidationError(
                'The given URL does not match valid image extensions.')

        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'
        responce = requests.get(image_url)
        image.image.save(image_name,
                         ContentFile(responce.content),
                         save=False)
        if commit:
            image.save()
        return image

app/images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpRequest, JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from .forms import ImageCreateForm
from .models import Image
from actions.utils import create_action
import redis
from django.conf import settings

r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)


@login_required
def image_create(request: HttpRequest):
    template_name = 'images/image/create.html'

    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user, 'bookmarked image', new_image)
            messages.success(request, 'Image added successfully')
            return redirect(new_image.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)

    context = {
        'form': form,
        'section': 'images'
    }

    return render(request=request, template_name=template_name, context=context)


def image_detail(request: HttpRequest, id: int, slug: str):
    template_name = 'images/image/detail.html'

    image = get_object_or_404(Image, id=id, slug=slug)

    total_views = r.incr(f'image:{image.id}:views')

    r.zincrby('image_ranking', 1, image.id)

    context = {
        'section': 'images',
        'image': image,
        'total_views': total_views
    }

    return render(request=request, template_name=template_name, context=context)


@login_required
@require_POST
def image_like(request: HttpRequest):
    image_id = request.POST.get('id')
    action = request.POST.get('action')

    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            pass

    return JsonResponse({'status': 'error'})


@login_required
def image_list(request: HttpRequest):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    images_only = request.GET.get('images_only')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)

    context = {
        'section': 'images',
        'images': images
    }

    if images_only:
        return render(request=request,
                      template_name='images/image/list_images.html',
                      context=context)

    return render(request=request,
                  template_name='images/image/list.html',
                  context=context)


@login_required
def image_ranking(request: HttpRequest):
    template_name = 'images/image/ranking.html'

    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]

    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))

    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))

    context = {
        'section': 'images',
        'most_viewed': most_viewed
    }

    return render(request=request, template_name=template_name, context=context)

app/images/templates/images/image/create.html
{% extends 'base.html' %}

{% block title %}Bookmark an image{% endblock %}

{% block content %}
<h1>Bookmark an image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Bookmark it!">
</form>
{% endblock %}

app/images/templates/images/image/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}

<h1>{{ image.title }}</h1>
<a href="{{ image.image.url }}">
    <img src="{% thumbnail image.image 300x0 quality=100 %}" class="image-detail">
</a>

{% with total_likes=image.users_like.count users_like=image.users_like.all %}
<div class="image-info">
    <div>
        <span class="count">
            <span class="total">{{ total_likes }}</span>
            like{{ total_likes|pluralize }}
        </span>
        <span class="count">
            {{ total_views }} view{{ total_views|pluralize }}
        </span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like"
            class="like button">
            {% if request.user in users_like %}
            Unlike
            {% else %}
            Like
            {% endif %}
        </a>
    </div>
    {{ image.description|linebreaks }}
</div>
<div class="image-likes">
    {% for user in users_like %}
    <div>
        {% if user.profile.photo %}
        <img src="{% thumbnail user.profile.photo 180x180 crop='smart' %}">
        {% else %}
        <img src="/media/users/no-photo.jpg" style="width: 180px; height: 180px;">
        {% endif %}
        <p>{{ user.first_name }}</p>
    </div>
    {% empty %}
    Nobody likes this image yet.
    {% endfor %}
</div>
{% endwith %}

{% endblock %}

{% block domready %}
const url = "{% url 'images:like' %}";
let options = {
method: 'POST',
headers: {'X-CSRFToken': csrftoken},
mode: 'same-origin'
}
document.querySelector('a.like').addEventListener('click', function(e){
e.preventDefault();
let likeButton = this;

let formData = new FormData();
formData.append('id', likeButton.dataset.id);
formData.append('action', likeButton.dataset.action);
options['body'] = formData;

fetch(url, options).then(responce => responce.json()).then(data => {
if (data['status'] === 'ok')
{
let previousAction = likeButton.dataset.action;

let action = previousAction === 'like' ? 'unlike' : 'like';
likeButton.dataset.action = action;
likeButton.innerHTML = action;

let likeCount = document.querySelector('span.count .total');
let totalLikes = parseInt(likeCount.innerHTML);
likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
}
})
});
{% endblock %}

app/images/templates/images/image/list.html
{% extends 'base.html' %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}
<h1>Images bookmarked</h1>
<div id="image-list">
    {% include 'images/image/list_images.html' %}
</div>
{% endblock %}

{% block domready %}
let page = 1;
let emptyPage = false;
let blockRequest = false;

window.addEventListener('scroll', function(e) {
let margin = document.body.clientHeight - window.innerHeight - 200;
if (window.pageYOffset > margin && !emptyPage && !blockRequest) {
blockRequest = true;
page += 1;

fetch('?images_only=1&page=' + page)
.then(responce => responce.text())
.then(html => {
if (html === '') {
emptyPage = true;
} else {
let imageList = document.getElementById('image-list');
imageList.insertAdjacentHTML('beforeEnd', html);
blockRequest = false;
}
})
}
});

const scrollEvent = new Event('scroll');
window.dispatchEvent(scrollEvent);
{% endblock %}

app/images/templates/images/image/list_images.html
{% load thumbnail %}

{% for image in images %}
<div class="image">
    <a href="{{ image.get_absolute_url }}">
        {% thumbnail image.image 300x300 crop="smart" as im %}
        <a href="{{ image.get_absolute_url }}">
            <img src="{{ im.url }}">
        </a>
    </a>
    <div class="info">
        <a href="{{ image.get_absolute_url }}" class="title">
            {{ image.title }}
        </a>
    </div>
</div>
{% endfor %}

app/images/templates/images/image/ranking.html
{% extends 'base.html' %}

{% block title %}Images ranking{% endblock %}

{% block content %}
<h1>Images ranking</h1>
<ol>
    {% for image in most_viewed %}
    <li>
        <a href="{{ image.get_absolute_url }}">
            {{ image.title }}
        </a>
    </li>
    {% endfor %}
</ol>
{% endblock %}